services:
  api:
    build: .
    container_name: ami-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/uploads
      - ws_logs:/app/logs

volumes:
  uploads_data:
  ws_logs:
