from .usuarios.usuario import User
from .usuarios.persona import Persona
from .usuarios.cliente import Cliente
from .usuarios.vehiculo import Vehiculo
from .usuarios.proveedor_servicio import ProveedorServicio
from .usuarios.rol import Rol
from .usuarios.usuario_rol import UsuarioRol
from .talleres.taller import Taller
from .talleres.catalogo_servicio import CatalogoServicio
